version: '3.8'
services:
  redis-az-tls:
    build: ./redis-az-ca
    restart: always
    ports:
      - '7000:6379'
    container_name: redis-az-ca
  redis-tls:
    image: redis:7.0.9-bullseye
    build: ./redis
    restart: always
    ports:
      - '7002:6379'
    container_name: redis-tls
    # volumes:
    #   - ./redis/tests/tls/redis.crt /usr/local/etc/redis/redis.crt
    #   - ./redis/tests/tls/redis.key /usr/local/etc/redis/redis.key
    #   - ./redis/tests/tls/ca.crt /usr/local/etc/redis/ca.crt 
#       - cache:/data
# volumes:
#   cache:
#    driver: local